# ================================
# DigitalOcean App Platform Configuration
# ================================
# Документація: https://docs.digitalocean.com/products/app-platform/reference/app-spec/

name: brainai-online
region: fra

# Налаштування для статичних маршрутів
static_sites: []

# Основний веб-сервіс
services:
  - name: web
    # GitHub репозиторій
    github:
      repo: AlanDeLan/BrainAi_online
      branch: main
      deploy_on_push: true
    
    # Використовуємо Dockerfile
    dockerfile_path: Dockerfile
    
    # Порт додатку
    http_port: 8000
    
    # Health check
    health_check:
      http_path: /health
      initial_delay_seconds: 10
      period_seconds: 30
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    
    # Налаштування інстансу
    instance_count: 1
    instance_size_slug: basic-xxs  # $5/місяць (512MB RAM, 1 vCPU)
    
    # Автоматичне масштабування (опціонально)
    # autoscaling:
    #   min_instance_count: 1
    #   max_instance_count: 3
    #   metrics:
    #     cpu:
    #       percent: 80
    
    # Змінні середовища
    envs:
      - key: PYTHON_VERSION
        value: "3.11"
        scope: RUN_TIME
      
      - key: ENVIRONMENT
        value: production
        scope: RUN_TIME
      
      - key: DEBUG
        value: "false"
        scope: RUN_TIME
      
      - key: AI_PROVIDER
        value: google_ai
        scope: RUN_TIME
      
      - key: OPENAI_BASE_URL
        value: https://api.openai.com/v1
        scope: RUN_TIME
      
      - key: CORS_ORIGINS
        value: '["https://brainai-online-xxxxx.ondigitalocean.app"]'
        scope: RUN_TIME
        type: GENERAL
      
      - key: RATE_LIMIT_PER_MINUTE
        value: "60"
        scope: RUN_TIME
      
      - key: RATE_LIMIT_PER_HOUR
        value: "1000"
        scope: RUN_TIME
      
      - key: LOG_LEVEL
        value: INFO
        scope: RUN_TIME
      
      # Секретні ключі (додайте вручну через Dashboard або doctl)
      - key: GOOGLE_API_KEY
        scope: RUN_TIME
        type: SECRET
      
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      
      - key: SESSION_SECRET
        scope: RUN_TIME
        type: SECRET
      
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET

# База даних PostgreSQL
databases:
  - name: brainai-db
    engine: PG
    version: "15"
    production: false  # false = Dev Database ($7/місяць), true = Production Database ($15/місяць)
    cluster_name: brainai-cluster

# Persistent storage для векторної БД
volumes:
  - name: vector-db-storage
    size: 1GiB  # 1 GB для ChromaDB/FAISS
    mount_path: /app/vector_db_storage

# Робочі процеси (workers, cron jobs)
workers: []

# Scheduled jobs (cron)
jobs: []

# Домени (додайте власний домен якщо потрібно)
domains: []
  # - domain: brainai.yourdomain.com
  #   type: PRIMARY
  #   zone: yourdomain.com

# Алерти та моніторинг
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
